version: "3"

services:
  trsc_db:
    container_name: trsc_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend_network
    restart: unless-stopped
# Il manque un healthcheck

  backend: # Il est ou LE VOLUME 
    container_name: backend # backend suffit
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile # Tu as quoi dans le dockerfile ?
    depends_on:
      - trsc_db
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:

volumes:
  database: