version: "3"

services:
  trsc_db:
    container_name: trsc_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend_network
    restart: unless-stopped
  # Il manque un healthcheck

  backend:
    container_name: backend 
    image: backend
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:migrate:dev
    ports:
      - 5001:5001
    depends_on:
      - trsc_db
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - ./upload:/usr/src/app/upload
      - /usr/src/app/node_modules
    networks:
      - backend_network
      - frontend_network
    restart: unless-stopped

  frontend:
    container_name: frontend 
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm run dev
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - ./upload:/usr/src/app/upload
      - ./frontend:/usr/src/app
    networks:
      - frontend_network
    restart: unless-stopped


networks:
  backend_network:
  frontend_network:

volumes:
  database: